version: '3.1'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: technator
      MYSQL_USER: technator
      MYSQL_PASSWORD: technator
    ports:
      - "3306:3306"
    volumes:
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: